# Generated by Django 5.0.4 on 2024-04-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='name',
            new_name='Username',
        ),
        migrations.AlterModelTable(
            name='mymodel',
            table='users',
        ),
    ]
