# Generated by Django 5.0.4 on 2024-04-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_name_mymodel_username_alter_mymodel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='users',
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
