# Generated by Django 5.0.4 on 2024-04-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_mymodel_users_alter_users_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='MyModel',
        ),
    ]
