# Generated by Django 5.0.4 on 2024-04-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_users'),
    ]

    operations = [
    ]
