# Generated by Django 5.0.4 on 2024-04-27 11:01

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20240427_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='year',
            field=models.DecimalField(decimal_places=2, default=builtins.any, max_digits=10),
            preserve_default=False,
        ),
    ]
