# Generated by Django 5.0.4 on 2024-04-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_mymodel_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='year',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='username',
            field=models.TextField(default=1, verbose_name=10),
            preserve_default=False,
        ),
    ]
