# Generated by Django 5.0.4 on 2024-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_delete_users_remove_mymodel_name_remove_mymodel_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='username',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
